#### Load the packages ####
library(conflicted)
library(data.table)
library(foreign)
library(openxlsx)
library(readxl)
library(readr)
library(sf)
library(geosphere)
library(Hmisc)
library(mgsub)
library(texreg)
library(lubridate)
library(zoo)
library(MatchIt)
library(fixest)
library(tidyverse)
library(naniar)
library(GSODR)
library(rmapshaper)
#
library(kableExtra)
library(scales)
#### Select the package when there are conflicts ####
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("isoweek", "lubridate")
conflict_prefer("yday", "lubridate")
conflict_prefer("month", "lubridate")
conflict_prefer("year", "lubridate")
